/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_rjdj_zengarden_ZGContext */

#ifndef _Included_me_rjdj_zengarden_ZGContext
#define _Included_me_rjdj_zengarden_ZGContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_rjdj_zengarden_ZGContext
 * Method:    newContext
 * Signature: (IIIF)J
 */
JNIEXPORT jlong JNICALL Java_me_rjdj_zengarden_ZGContext_newContext
  (JNIEnv *, jobject, jint, jint, jint, jfloat);

/*
 * Class:     me_rjdj_zengarden_ZGContext
 * Method:    deleteContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_rjdj_zengarden_ZGContext_deleteContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_rjdj_zengarden_ZGContext
 * Method:    newGraph
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_me_rjdj_zengarden_ZGContext_newGraph__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_rjdj_zengarden_ZGContext
 * Method:    newGraph
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_me_rjdj_zengarden_ZGContext_newGraph__Ljava_lang_String_2Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     me_rjdj_zengarden_ZGContext
 * Method:    registerReceiver
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_me_rjdj_zengarden_ZGContext_registerReceiver
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     me_rjdj_zengarden_ZGContext
 * Method:    unregisterReceiver
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_me_rjdj_zengarden_ZGContext_unregisterReceiver
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     me_rjdj_zengarden_ZGContext
 * Method:    process
 * Signature: (I[SI[SIJ)V
 */
JNIEXPORT void JNICALL Java_me_rjdj_zengarden_ZGContext_process
  (JNIEnv *, jobject, jint, jshortArray, jint, jshortArray, jint, jlong);

/*
 * Class:     me_rjdj_zengarden_ZGContext
 * Method:    sendMessage
 * Signature: (Ljava/lang/String;Lme/rjdj/zengarden/Message;J)V
 */
JNIEXPORT void JNICALL Java_me_rjdj_zengarden_ZGContext_sendMessage
  (JNIEnv *, jobject, jstring, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
