/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_rjdj_zengarden_ZGObject */

#ifndef _Included_me_rjdj_zengarden_ZGObject
#define _Included_me_rjdj_zengarden_ZGObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_rjdj_zengarden_ZGObject
 * Method:    remove
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_rjdj_zengarden_ZGObject_remove
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_rjdj_zengarden_ZGObject
 * Method:    sendMessage
 * Signature: (ILme/rjdj/zengarden/Message;J)V
 */
JNIEXPORT void JNICALL Java_me_rjdj_zengarden_ZGObject_sendMessage
  (JNIEnv *, jobject, jint, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
