# -O3 optimise!
# -g3 -ggdb3 debug!
gcc -o ../libs/osx/libjnizengarden.jnilib -fPIC -O3 -dynamiclib \
-I./ \
-I./me/rjdj/zengarden/ \
-I/Developer/SDKs/MacOSX10.5.sdk/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Headers \
-I../../libsndfile-1.0.20/src/ \
-L../../libsndfile-1.0.20/src/.libs/ \
./me/rjdj/zengarden/jnizengarden.cpp \
./DspAdd.cpp \
./DspAdc.cpp \
./DspBandpassFilter.cpp \
./DspBinaryOperationObject.cpp \
./DspClip.cpp \
./DspDac.cpp \
./DspDelayRead.cpp \
./DspDelayWrite.cpp \
./DspDivide.cpp \
./DspHighpassFilter.cpp \
./DspInletOutlet.cpp \
./DspInputDspOutputObject.cpp \
./DspInputMessageOutputObject.cpp \
./DspMessageInputDspOutputObject.cpp \
./DspMessageInputMessageOutputObject.cpp \
./DspLine.cpp \
./DspLog.cpp \
./DspLowpassFilter.cpp \
./DspMultiply.cpp \
./DspOsc.cpp \
./DspOutputObject.cpp \
./DspNoise.cpp \
./DspPhasor.cpp \
./DspSendReceive.cpp \
./DspSig.cpp \
./DspSubtract.cpp \
./DspTable.cpp \
./DspTableRead.cpp \
./DspVariableDelay.cpp \
./DspVCF.cpp \
./List.cpp \
./MessageAbsoluteValue.cpp \
./MessageAdd.cpp \
./MessageArcTangent2.cpp \
./MessageBang.cpp \
./MessageBinaryOperationObject.cpp \
./MessageChange.cpp \
./MessageClip.cpp \
./MessageCosine.cpp \
./MessageDbToPow.cpp \
./MessageDbToRms.cpp \
./MessageDelay.cpp \
./MessageDivide.cpp \
./MessageElement.cpp \
./MessageEnv.cpp \
./MessageExp.cpp \
./MessageEqualsEquals.cpp \
./MessageExternalSend.cpp \
./MessageFloat.cpp \
./MessageFrequencyToMidi.cpp \
./MessageGreaterThan.cpp \
./MessageGreaterThanOrEqualTo.cpp \
./MessageInletOutlet.cpp \
./MessageInputDspOutputObject.cpp \
./MessageInputMessageOutputObject.cpp \
./MessageInteger.cpp \
./MessageLessThan.cpp \
./MessageLessThanOrEqualTo.cpp \
./MessageLine.cpp \
./MessageLoadbang.cpp \
./MessageLog.cpp \
./MessageLogicalAnd.cpp \
./MessageLogicalOr.cpp \
./MessageMessageBox.cpp \
./MessageMetro.cpp \
./MessageMidiToFrequency.cpp \
./MessageModulus.cpp \
./MessageMoses.cpp \
./MessageMultiply.cpp \
./MessageNotEquals.cpp \
./MessagePack.cpp \
./MessagePow.cpp \
./MessagePowToDb.cpp \
./MessagePrint.cpp \
./MessageOutputObject.cpp \
./MessageRandom.cpp \
./MessageRmsToDb.cpp \
./MessageRoute.cpp \
./MessageSelect.cpp \
./MessageSendReceive.cpp \
./MessageSine.cpp \
./MessageSpigot.cpp \
./MessageSoundfiler.cpp \
./MessageSqrt.cpp \
./MessageSubtract.cpp \
./MessageSwap.cpp \
./MessageSymbol.cpp \
./MessageTangent.cpp \
./MessageTimer.cpp \
./MessageToggle.cpp \
./MessageTrigger.cpp \
./MessageUnaryOperationObject.cpp \
./MessageUnpack.cpp \
./PdGraph.cpp \
./PdMessage.cpp \
./PdObject.cpp \
./RemoteBufferObject.cpp \
./RemoteBufferReceiverObject.cpp \
./StaticUtils.cpp \
./TextObject.cpp \
-lstdc++ -lsndfile

rm *.o
cp ../libs/osx/libjnizengarden.jnilib /Library/Java/Extensions
ls -l ../libs/osx/libjnizengarden.jnilib